### ISSUE TITLE
Grayskull no longer finds the entry_points and deps on depfinder

### ISSUE THREAD

**Issue by CJ-Wright** [marcelotrevisani/grayskull#158]
Grayskull 0.7.0 used to find the [depfinder entry points](https://github.com/ericdill/depfinder/blob/master/setup.py#L18) but now it seems like it doesn't.

**Comment by marcelotrevisani** [comment]
I cannot reproduce this problem with ``0.7.3``
Please see:
https://marcelotrevisani.info:8000/recipe/?name=depfinder

**Comment by marcelotrevisani** [comment]
Can we close it? or is it generating the recipe without the ``entry_points`` with ``0.7.3``?

**Comment by CJ-Wright** [comment]
Using the CLI `grayskull pypi depfinder` produced:
```yaml
{% set name = "depfinder" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 813c68ef13d75305120d614a3822edfd7b5e660edb99f6a0ae59f3fae00cff28

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - depfinder
  commands:
    - pip check
  requires:
    - pip

about:
  home: http://github.com/ericdill/depfinder
  summary: Find all the imports in your library
  doc_url: https://pythonhosted.org/depfinder/
  license: BSD-3-Clause
  license_file: LICENSE
extra:
  recipe-maintainers:
    - AddYourGitHubIdHere
```

`grayskull --version` produced:
`0.7.3`

**Comment by marcelotrevisani** [comment]
Oh That is pretty odd
It is working on my machine, I am using Ubuntu 20.04
What OS and version are you using? What is your locale? Which terminal did you try to execute that?

**Comment by marcelotrevisani** [comment]
If I have to guess, it is raising an exception and it is blocking grayskull to get the metadata from sdist.
Because the dependencies are also missing, look
```
➜ grayskull --version
0.7.3

➜ grayskull pypi depfinder
#### Initializing recipe for depfinder (pypi) ####

Recovering metadata from pypi...
Starting the download of the sdist package depfinder-2.3.1.tar.gz
depfinder-2.3.1.tar.gz 100% Time:  0:00:00   2.1 MiB/s|#########################################################################################|
Recovering information from setup.py
Executing injected distutils...
Recovering metadata from setup.cfg
Checking >> stdlib-list 100% |###########################################################################################|[Elapsed Time: 0:00:00]
Recovering license info from spdx.org ...
Matching license file with database from Grayskull...
License type: BSD-3-Clause
License file: LICENSE
Host requirements:
  - pip
  - python

Run requirements:
  - python
  - pyyaml
  - stdlib-list

RED: Missing packages
GREEN: Packages available on conda-forge
Maintainers:
   - marcelotrevisani

#### Recipe generated on /home/bb8/deletar for depfinder ####


```
```
➜ cat depfinder/meta.yaml
```
```yaml
{% set name = "depfinder" %}
{% set version = "2.3.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 813c68ef13d75305120d614a3822edfd7b5e660edb99f6a0ae59f3fae00cff28

build:
  number: 0
  noarch: python
  entry_points:
    - depfinder = depfinder.cli:cli
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pyyaml
    - stdlib-list

test:
  imports:
    - depfinder
  commands:
    - pip check
    - depfinder --help
  requires:
    - pip

about:
  home: http://github.com/ericdill/depfinder
  summary: Find all the imports in your library
  doc_url: https://pythonhosted.org/depfinder/
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - marcelotrevisani
```
