### ISSUE TITLE
Allow passing a package mapping for pypi->conda-forge packages

### ISSUE THREAD

**Issue by mariusvniekerk** [marcelotrevisani/grayskull#168]
We should have some way of having a mapping where pypi package names (such as `docker` vs `docker-py`) can be mapped from pypi names to conda names.

**Comment by marcelotrevisani** [comment]
We do have it on ``grayskull`` :)
Please see
https://github.com/marcelotrevisani/grayskull/blob/master/grayskull/pypi/config.yaml

**Comment by marcelotrevisani** [comment]
So we will need to just add a new entry to that file, something like
```yaml
docker:
  import_name: docker
  conda_forge: docker-py
```

**Comment by marcelotrevisani** [comment]
Do you know other differences of project names between pypi and conda-forge?
I just have a few in that file

**Comment by mariusvniekerk** [comment]
We can probably back it out of the feedstock graph + libcfgraph

**Comment by marcelotrevisani** [comment]
I don't know what you mean, sorry
Can you explain a bit more please?

**Comment by mariusvniekerk** [comment]
going to take a shot at generating this automatically from our metadata in https://github.com/regro/cf-graph-countyfair/tree/master/node_attrs

**Comment by mariusvniekerk** [comment]
So looking at the conda-forge metadata i can generate a list of 174 packagest that have a `non-case` mismatch between `conda-forge` and `pypi` name.

**Comment by mariusvniekerk** [comment]
we can probably generate this automatically as part of the conda-forge bot and publish it to github somewhere?

**Comment by mariusvniekerk** [comment]
<details>
<summary>Automatically found mismatches</summary>

```yaml
Boruta:
  conda_forge: boruta_py
  import_name: boruta
Flask-Cors:
  conda_forge: flask_cors
  import_name: flask_cors
Flask-JSON:
  conda_forge: flask_json
  import_name: flask_json
SoundFile:
  conda_forge: pysoundfile
  import_name: soundfile
aiohttp_cors:
  conda_forge: aiohttp-cors
  import_name: aiohttp_cors
backtrace:
  conda_forge: python-backtrace
  import_name: backtrace
bash_completion:
  conda_forge: py-bash-completion
  import_name: bash_completion
captest:
  conda_forge: pvcaptest
  import_name: captest
cdo:
  conda_forge: python-cdo
  import_name: cdo
click_config_file:
  conda_forge: click-config-file
  import_name: click_config_file
cockroachdb:
  conda_forge: cockroachdb-python
  import_name: cockroachdb
conda_lock:
  conda_forge: conda-lock
  import_name: conda_lock
conda_mirror:
  conda_forge: conda-mirror
  import_name: conda_mirror
coreapi:
  conda_forge: python-coreapi
  import_name: coreapi
coreschema:
  conda_forge: python-coreschema
  import_name: coreschema
cryptography_vectors:
  conda_forge: cryptography-vectors
  import_name: cryptography_vectors
cufflinks:
  conda_forge: python-cufflinks
  import_name: cufflinks
dask:
  conda_forge: dask-core
  import_name: dask
datadotworld:
  conda_forge: datadotworld-py
  import_name: datadotworld
datalad_container:
  conda_forge: datalad-container
  import_name: datalad_container
delegator.py:
  conda_forge: delegator
  import_name: delegator
dials_data:
  conda_forge: dials-data
  import_name: dials_data
dye_score:
  conda_forge: dye-score
  import_name: dye_score
empyrical_dist:
  conda_forge: empyrical-dist
  import_name: empyrical_dist
esprima:
  conda_forge: esprima-python
  import_name: esprima
et_xmlfile:
  conda_forge: et-xmlfile
  import_name: et_xmlfile
evalml:
  conda_forge: evaml-core
  import_name: evalml
extract-msg:
  conda_forge: msg-extractor
  import_name: extract_msg
flake8_nb:
  conda_forge: flake8-nb
  import_name: flake8_nb
flatbuffers:
  conda_forge: python-flatbuffers
  import_name: flatbuffers
flex:
  conda_forge: flex-swagger
  import_name: flex
gnupg:
  conda_forge: gnupg-py
  import_name: gnupg
google:
  conda_forge: googlesearch
  import_name: googlesearch
graphviz:
  conda_forge: python-graphviz
  import_name: graphviz
h2o:
  conda_forge: h2o-py
  import_name: h2o
hdfs:
  conda_forge: python-hdfs
  import_name: hdfs
iam_units:
  conda_forge: iam-units
  import_name: iam_units
ib_insync:
  conda_forge: ib-insync
  import_name: ib_insync
intake-astro:
  conda_forge: intake-accumulo
  import_name: intake_astro
intake_geopandas:
  conda_forge: intake-geopandas
  import_name: intake_geopandas
ioos_tools:
  conda_forge: ioos-tools
  import_name: ioos_tools
jupyter_jaeger:
  conda_forge: jupyter-jaeger
  import_name: jupyter_jaeger
jupyterlab_git:
  conda_forge: jupyterlab-git
  import_name: jupyterlab_git
jupyterlab_latex:
  conda_forge: jupyterlab-latex
  import_name: jupyterlab_latex
libaio:
  conda_forge: python-libaio
  import_name: libaio
md_toc:
  conda_forge: md-toc
  import_name: md_toc
message_ix:
  conda_forge: message-ix
  import_name: message_ix
mss:
  conda_forge: python-mss
  import_name: mss
nbconvert_utils:
  conda_forge: nbconvert-utils
  import_name: nbconvert_utils
ndarray_listener:
  conda_forge: ndarray-listener
  import_name: ndarray_listener
neo:
  conda_forge: python-neo
  import_name: neo
nest_asyncio:
  conda_forge: nest-asyncio
  import_name: nest_asyncio
node-semver:
  conda_forge: python-node-semver
  import_name: semver
nvidia-ml-py3:
  conda_forge: nvidia-ml
  import_name: pynvml
pandas_flavor:
  conda_forge: pandas-flavor
  import_name: pandas_flavor
paragraph:
  conda_forge: python-paragraph
  import_name: paragraph
prince:
  conda_forge: prince-factor-analysis
  import_name: prince
pvlib:
  conda_forge: pvlib-python
  import_name: pvlib
pyct:
  conda_forge: pyct-core
  import_name: pyct
pytest_check_links:
  conda_forge: pytest-check-links
  import_name: pytest_check_links
python-datamatrix:
  conda_forge: datamatrix
  import_name: datamatrix
python-fileinspector:
  conda_forge: fileinspector
  import_name: fileinspector
python-pseudorandom:
  conda_forge: pseudorandom
  import_name: pseudorandom
python-pygaze:
  conda_forge: pygaze
  import_name: pygaze
python-qdatamatrix:
  conda_forge: qdatamatrix
  import_name: qdatamatrix
python-qnotifications:
  conda_forge: qnotifications
  import_name: QNotifications
quantum-grove:
  conda_forge: grove
  import_name: grove
radio_beam:
  conda_forge: radio-beam
  import_name: radio_beam
rocketpyalpha:
  conda_forge: rocketpy
  import_name: rocketpy
sage_flatsurf:
  conda_forge: sage-flatsurf
  import_name: flatsurf
sagemaker_inference:
  conda_forge: sagemaker-inference-toolkit
  import_name: sagemaker_inference
sagemaker_mxnet_training:
  conda_forge: sagemaker_mxnet_container
  import_name: sagemaker_mxnet_container
sounddevice:
  conda_forge: python-sounddevice
  import_name: sounddevice
spherical-functions:
  conda_forge: spherical_functions
  import_name: spherical_functions
stjudecloud-oliver:
  conda_forge: oliver
  import_name: oliver
termstyle:
  conda_forge: python-termstyle
  import_name: termstyle
torch_geometric:
  conda_forge: pytorch_geometric
  import_name: torch_geometric
useDAVE:
  conda_forge: dave
  import_name: numpy
vsts:
  conda_forge: vsts-python-api
  import_name: vsts
```

</details>
